### ISSUE TITLE
Suggestion: seperate keyword triggers for doubled up settings panes

### ISSUE THREAD

**Issue by a-rock-lobster** [alfredapp/system-settings-workflow#1]
Hullo, 

Thank you for setting this workflow up. The mess created with ventura, mostly the mistargeted settings panes, was really bothering me and messing up automations. 

I've made a tiny change to the workflow for myself that I thought I would share as I think it makes the workflow a tad more intuitive. 

Simply, for preference panes which serve more than one setting, for example "dock & desktop" or "date & time", I seperated the keyword triggers i.e. one for "date" and another for "time", but they are still pointed to the same arguament. I did this because I often forget which comes first and typing "time" doesn't work with the original set up (you have to type date). Same icon and everything, just a different keyword.

Thanks again,

**Comment by a-rock-lobster** [comment]
Well, I've just seen that this has just been implemented 11 hours ago 😅

**Comment by a-rock-lobster** [comment]
I think the latest update was supposed to replace the need for splitting by using || seperators. But when I update or clean install this isn't the case. It rather goes back to the pre-split behaviour.

**Comment by vitorgalvao** [comment]
Where are you installing from? What’s the workflow version you’re using? Which keywords are you having trouble with?

**Comment by a-rock-lobster** [comment]
I have tried installing both from github and the gallery. 
2023.1
Basically any which hand and "and" or "or" i.e. transfer or reset. 

I presume the latest update was supposed to change the keyword to "transfer || reset" rather than having two seperate keyword inputs. For me atleast, it leaves it as "transfer or reset" whilst also removing the second keyword input for "reset". Thus, typing resest into alfred returns nothing. 

It's easy enough to go through and manually replace and/or with || so I'm not having any trouble.

**Comment by vitorgalvao** [comment]
Something that may have happened is that you customised the keywords before and when installing the new version left checked the box to `Migrate my workflow customisations`. Look on the bottom left when installing the workflow and make sure to untick the checkbox.

Alternatively, delete the workflow and *then* install it (instead of updating what’s already installed).

**Comment by a-rock-lobster** [comment]
Sorry, yes you were right, that was the cause. I should stop trying to be helpful 😅
