### ISSUE TITLE
Probably a misspelled

### ISSUE THREAD

**Issue by elvisgastelum** [alfredapp/system-settings-workflow#2]
### Workflow version

v2023.1

### Alfred version

5.1.1 (2138)

### macOS version

13.0

### Debugger output

```alfred_debugger
n/a
```

### More details

I noticed the "Control Center" option was misspelled with the word "Control Centre", i don't know if that's incorrect or on purpose, that can be easily changed manually, but is still a misspelled. it don't affect to the functionality on any aspect.

**Comment by vitorgalvao** [comment]
In this case it’s on purpose, the official workflows use the British English spelling.

But thank you for the report, even typo notices are quite welcome!
