### ISSUE TITLE
Feature request: Prepend a "prefix" to the keyword

### ISSUE THREAD

**Issue by notDavid** [alfredapp/system-settings-workflow#3]
### Workflow version

2023.1

### Alfred version

5.1.1

### macOS version

13.4

### Debugger output

```alfred_debugger
-
```

### More details

Hi there,

please consider adding an option to prepend a prefix to ALL keywords. So for example if i set a prefix `s.` then just typing `s.` in Alfred would reveal **ALL** other keywords/settings of this workflow.

For example, the `about` keyword would become `s.about`

Thank you!

**Comment by vitorgalvao** [comment]
That’s out of scope for this workflow. There is [another](https://alfred.app/workflows/stephenc/open-macos-settings-panes/) which works like you want.

**Comment by notDavid** [comment]
Okay i see, thank you for the suggestion.
