### ISSUE TITLE
Multiple Keyword for Setting with Multiple Categories

### ISSUE THREAD

**Issue by qoomon** [alfredapp/system-settings-workflow#6]
### Feature details

It would be awesome if you can add separate keyword inputs for settings like `Privacy & Security` and provide separate keywords, e.g. `privacy` and `security`. 

**Following settings consist of multiple categories:**
- `Privacy & Security`
- `Siri & Spotlight`
- `Touch ID & Password`
- `Users & Groups`
- `Wallet & Apple Pay`
- `Printers & Scanners`

**Comment by qoomon** [comment]
Probably the easiest solution is just to use the multiple keyword feature by separating them with `||` e.g. `privacy||security`

**Comment by vitorgalvao** [comment]
That’s exactly how it works. If it’s not how it’s behaving for you, update the workflow.

**Comment by vitorgalvao** [comment]
That’s exactly how it works. If it’s not how it’s behaving for you, you’re either using an old version or changed the keywords yourself.

See also https://github.com/alfredapp/system-settings-workflow/issues/1

**Comment by qoomon** [comment]
Thx
