### ISSUE TITLE
Add AppleCare & Warranty settings pane

### ISSUE THREAD

**Issue by FireFingers21** [alfredapp/system-settings-workflow#7]
### Feature details

In macOS Sonoma 14.1, a new `AppleCare & Warranty` settings pane was added under System Settings → General → AppleCare & Warranty. Its URL Scheme is `x-apple.systempreferences:com.apple.Coverage-Settings.extension`. Could it be added to the workflow?

**Comment by vitorgalvao** [comment]
Added in [2024.1](https://github.com/alfredapp/system-settings-workflow/releases/tag/2024.1). Will be live in the Gallery later today.
